{-|
Database representation of org-mode data. All types are generated by
persistent-template. The naming and the structure tries to mimick the
orgmode-parse types as much as possible.

A 'Document' represents a org-mode file/document. 1 'Document' can have
ordinary text data as well as 0..* 'Heading's. The relation between
'Heading's and a 'Document' is saved in the 'Heading' using a foreign key of
the 'Document' ID (AKA one-to-many relationship).

Since 'Heading's have a tree structure, 1 'Heading' can have 0..* children
'Heading's. This relationship is saved in the child 'Heading' using a foreign
key of the parent 'Heading' ID (AKA one-to-many relationship).

Each 'Heading' can have 0..* 'Tag's. The name of a 'Tag' is unique and is shared
among multiple 'Heading's. This relationship is saved in the separate 'TagRel'
item that contains the ID to the owner 'Heading' and the ID to the 'Tag'
(AKA many-to-many relationship).

1 'Heading' have 1 'Section', which is saved in the 'Heading' using a
foreign key of the 'Section' ID (AKA one-to-one relationship).

1 'Section' can have 0..* 'Clock's. This relationship is saved in the 'Clock'
using a foreign key of the 'Section' ID (AKA one-to-many relationship).
-}

module Database.OrgMode.Model where

import           Database.OrgMode.Import

--------------------------------------------------------------------------------

share [mkPersist sqlSettings, mkMigrate "migrateAll"] [persistLowerCase|
Document json
    name Text
    text Text
    UniqueDocument name
    deriving Show

Section json
    paragraph Text
    deriving Show

Heading json
    level Int
    keyword Text Maybe
    title Text
    section SectionId
    parent HeadingId Maybe
    document DocumentId
    deriving Show

Clock json
    owner SectionId
    start UTCTime
    end UTCTime Maybe
    duration Int
    deriving Show

Tag json
    name Text
    UniqueTag name
    deriving Show

TagRel json
    owner HeadingId
    item TagId
    deriving Show
|]
